spring: #띄어쓰기 없음
  profiles:
    active: local
  datasource: #띄어쓰기 2칸
    jdbcurl: jdbc:h2:tcp://localhost/~/lguplus #4칸
    username: sa
    password:
    driver-class-name: org.h2.Driver
  secondary-datasource: #띄어쓰기 2칸
    jdbcurl: jdbc:h2:tcp://localhost/~/test #4칸
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa: #띄어쓰기 2칸
    hibernate: #띄어쓰기 4칸
      ddl-auto: none #띄어쓰기 6칸
    properties: #띄어쓰기 4칸
      hibernate: #띄어쓰기 6칸
        # show_sql: true #띄어쓰기 8칸
        format_sql: true #띄어쓰기 8칸
        default_batch_fetch_size: 100
#        use_sql_comments: true

#  thymeleaf:
#     cache: false
#      prefix: classpath:/templates/
#    open-in-view: false
logging.level: #띄어쓰기 없음
  org.hibernate.SQL: debug #띄어쓰기 2칸
#  org.hibernate.type: trace #띄어쓰기 2칸

server:
  error:
   inculde-exception: true
   include-message: always
   include-statctrace: always
   include-binding: always

mybatis:
  mapper-locations: /mapper/**/*.xml
  type-aliases-package: maven.com.lguplus.mybatis